name: Render-Video

on:
  workflow_dispatch:
    inputs:
      name:
        description: "video Name"
        required: true
      formData:
        description: "FormData for the video"
        required: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Chrome Headless Shell
        uses: actions/cache@v3
        with:
          path: ~/.cache/remotion
          key: ${{ runner.os }}-remotion-chrome-shell
          restore-keys: |
            ${{ runner.os }}-remotion

      - name: Install dependencies
        run: |
          npm i bun -g
          bun install

      - name: Render video
        run: |
          mkdir -p output
          bunx remotion render src/remotion/index.ts YogaDay output/out.mp4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-${{ github.event.inputs.name }}
          path: output/out.mp4
