name: Render-Video

on:
  workflow_dispatch:
    inputs:
      name:
        description: "video Name"
        required: true
      formData:
        description: "FormData for the video"
        required: true
      renderId:
        required: true
        description: 'Unique ID for the video render'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: |
          npm i bun -g
          bun install

      - name: Render video
        env:
          MY_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
        run: |
          mkdir -p output
          echo "Using secret key: $MY_SECRET_KEY"
          echo "Rendering video with ID: ${{ github.event.inputs.renderId }}"
          echo "Rendering formData with ID: ${{ github.event.inputs.formData }}"
          bunx remotion render src/remotion/index.ts YogaDay output/${{ github.event.inputs.renderId }}.mp4 --props='${{ github.event.inputs.formData }}'


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-${{ github.event.inputs.renderId }}
          path: output/${{ github.event.inputs.renderId }}.mp4
